<a href="https://colab.research.google.com/github/hwasser95/myhw/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# #1
 (10 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [2]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
l=[]
for i in a:
  if [i] in b:
    l.append(i)
print(set(l))
  


{2, 4}


# #2
 (10 Points) ​Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionalityso that you do not need to explicitly key in every integer value

In [3]:
ac=np.arange(1,16,1)
ac1=ac.reshape(5,3,order='f')
print(ac1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


# #3
The process of transforming a multidimensional array into a unidimensional array is referred to as“flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence ofvalues contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [4]:
az=ac.flatten(order='f')
print(az)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# #4
Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column
becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and
the third column becomes the third dimension of the 3-D array.


In [5]:
ac2=ac.reshape(1,5,3,order='f')
print(ac2.T)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [ ]:
#or 
print(ac2)

[[[ 1  6 11]
  [ 2  7 12]
  [ 3  8 13]
  [ 4  9 14]
  [ 5 10 15]]]


# #5
​Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2


In [7]:
az1=ac2.flatten(order='f')
az1=az1.reshape(5,3,order='f')

print(az1)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


# #6
 ​You are given the following two arrays:a = np.array([12, 5, 7, 15, 3, 1, 8])b = np.array([14, 6, 3, 11, 19, 12, 5])

Write a Python/Numpy code block that removes from array ​a ​any items that are also present in array b

In [ ]:
a1 = np.array([12, 5, 7, 15, 3, 1, 8])
b1 = np.array([14, 6, 3, 11, 19, 12, 5])
l=[]
for i in a1:
  if i not in b1:
   l.append(i)
a1=np.array(l)
print(a1)

[ 7 15  1  8]


# #7

In [ ]:
import pandas as pd
import numpy as np
#nyc_water
# supress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shownbelow 
# with a link to the “raw” version of the file you pushed to your online GitHub repository
ny = pd.read_csv('https://raw.githubusercontent.com/hwasser95/myhw/main/cityData.csv').to_numpy()
# verify you have an ndarray object
type(ny)
print(ny.shape)

(39, 4)


In [ ]:
#I’m splitting all the columns into individual list in order to easily manage the lists 
#Year
ny1=ny[:,0:1]
#New York City Population	
ny2=ny[:,1:2]
#NYC Consumption(Million gallons per day)
ny3=ny[:,2:3]
#Per Capita(Gallons per person per day)
ny4=ny[:,3:4]
ny1.max()
 

2017.0

## #A
What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [ ]:
#I’m going to find the max from column 3
ny3.max()

1512.0

## #B
How many calendar years are represented within this data set? NumPy's ​shape ​command is one way to findout.

In [ ]:
# The len of ny1 will count how many years 
print(len(ny1))

39


## #C
​What is the mean and the standard deviation of the per capita daily water consumption?



In [ ]:
#Using ny4 array that has the per capita daily water consumption
ny4.mean()

160.30769230769232

In [ ]:
ny4.std()

31.51894330370624

## #D
What is the increase or decrease in population from year to year? Use NumPy's `​diff` ​function to create an array  ofdifferences and save that to a variable called "​pop_diff​", then print that variable to the screen.

In [ ]:
#Using ny2 array that has the different populations 
pop_diff=np.diff(ny2,axis=0)
print(pop_diff)

[[-30461. ]
 [ 17602. ]
 [ 19864. ]
 [ 72119. ]
 [ 53290. ]
 [ 39540. ]
 [ 45192. ]
 [ 23230. ]
 [ 11243. ]
 [ -9544. ]
 [ -8525. ]
 [ 38851. ]
 [ 54443. ]
 [ 77222. ]
 [ 64292. ]
 [ 62582. ]
 [ 64772. ]
 [ 75631. ]
 [ 84816. ]
 [ 89401. ]
 [ 60618. ]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [108965. ]
 [ 77081. ]
 [ 61281. ]
 [ 49530. ]
 [ 44512. ]
 [ 21171. ]
 [ 85025. ]]
